stages:
  - build
  - test
  - package
  - deploy

build_job:
  stage: build
  script:
    - cd User.API
    - dotnet build

test_job:
  stage: test
  script:
   - cd User.API.Tests
   - dotnet test

package_job:
  stage: package
  only: master
  script:
   - cd User.API
   - docker build -t userapi:v1 .
   - docker login -u ${username} -p ${password} ${registry}
   - docker tag userapi:v1 registry.cn-shanghai.aliyuncs.com/jonny_microservice/user_api:v1
   - docker push registry.cn-shanghai.aliyuncs.com/jonny_microservice/user_api:v1

#deploy_job:
  #stage: deploy
  #script:
  # - docker run -d -p 5008:80  --link mysql01:db --name userapi:v1 userapi:v1
