stages:
  - build
  - test
  - package
  - deploy

build_job:
  stage: build
  script:
    - cd User.API
    - dotnet build

test_job:
  stage: test
  script:
   - cd User.API.Tests
   - dotnet test

package_job:
  stage: package
  script:
   - cd User.API
   - docker build -t userapi:v1 .
   - docker login -u ${username} -p ${password} ${registry}
   - docker tag ${repo}:v1
   - docker push ${repo}:v1

deploy_job:
  stage: deploy
  script:
   - docker rm mysql01 -f
   - docker run -d -p 8080:80  --link mysql01:db --name userapi userapi:v1
