version: '3.4'

services:
  web: 
    build: .
    container_name: 'aspnetcore'
    ports:
      - '5004:5002'
    depends_on:
      - db
  db: 
    image: mysql/mysql-server
    container_name: 'mysql'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    ports:
      - '3006:3006'
    environment:
      MYSQL_USER: jesse
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456 
    volumes:
      - /my/mysql/conf:/etc/mysql/mysql.conf.d
      - /my/mysql/data:/var/lib/mysql
      - /my/mysql/logs:/logs